language: c

sudo: false

matrix:
  - os: linux
    sudo: false
  - os: osx
    osx_image: xcode10.3
    addons:
      homebrew:
        update: true
        packages:
          - flex
          - gperf
          - bison

env:
  - MRUBY_CONFIG=travis_config.rb
script: "rake -m && rake test"
